LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import urls
from books.views import signup,landing_page

urlpatterns = [
    path('', landing_page),
    path('admin/', admin.site.urls),
    path('books/',  include('books.urls')),
    path('',include(urls)),
    path('signup/', signup, name='signup')
]

books/urls.py
from django.urls import path
from books.views import index, details, create, update, delete

app_name = 'books'

urlpatterns = [
    path('',index, name='index'),
    path('create/',create, name='create'),
    path('<int:id>/',details, name='details'),
    path('<int:id>/delete/',delete, name='delete'),
    path('<int:id>/update/',update, name='update'),
]

books/models.py
from django.db import models

# Create your models here.
class Book(models.Model) :
    title = models.CharField(max_length= 40)
    author = models.CharField(max_length=40)
    price = models.DecimalField(max_digits=10, decimal_places=3)

    def __str__(self):
        return self.title

books/views.py
from contextlib import redirect_stderr
import imp
from wsgiref.util import request_uri
from django.shortcuts import render, redirect
from books.models  import Book
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def landing_page(request) :
    return render(request, 'landing.html')
@login_required
def index(request) :
    books=Book.objects.all()
    return render (request, 'books/index.html', {'Books':books})

@login_required
def details(request, id) :
    books=Book.objects.get(id=id)
    print(books)
    return render (request, 'books/details.html', {'books':books})

@login_required
def create (request) :
    if request.POST :
        new_book= Book(title=request.POST['title'],author=request.POST['author'],price=request.POST['price'])
        new_book.save()
        return redirect('/books')
    return render(request, 'books/create.html')

@login_required
def update(request, id) :
    books=Book.objects.get(id=id)
    if request.POST :
        new_book= Book(title=request.POST['title'],author=request.POST['author'],price=request.POST['price'])
        new_book.save()
        books.delete()
        return redirect('/books')
    return render (request, 'books/update.html', {'books':books})

@login_required
def delete(request, id) :
    books=Book.objects.get(id=id)
    books.delete()
    return redirect('/books/')

def signup(request) :
    if request.POST:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    form=UserCreationForm()
    return render(request, 'registration/signup.html', {'form' : form})

books/templates/books/create.html
{% extends 'base.html' %}

{% block title %}
Create
{% endblock title %}

{% block style %}
input{
    margin: 3px;
    border-radius: 5px;
    border: solid 1px;
}
form{
    margin-bottom: 10px;

}
p{
    font-size: 20px;
}
button{
    width: 150px;
    height: 30px;
    background-color:black;
    border-radius: 7px;
}
button a{
    text-decoration: none;
    color:white;
    font-size: 15px;
}
#save{
    width: 150px;
    height: 30px;
    background-color:black;
    border-radius: 7px;
    color: white;
    font-size: 15px;
}
{% endblock style %}

{% block content %}
<h1>Add New Book</h1>
        <form method="post">
        {% csrf_token %}
        <p>Name : <input type="text" name="title"><br>
        Author : <input type="text" name="author"><br>
        Price : <input type="number" name="price"><br></p>
        <button><a href="{% url 'books:index' %}">Back</a></button>
        <input id="save" type="submit" value="Save">
    </form>
{% endblock content %}

books/templates/books/details.html
{% extends 'base.html' %}

{% block title %}
Details
{% endblock title %}

{% block style %}
button{
    width: 150px;
    height: 30px;
    background-color:black;
    border-radius: 7px;
}
a button{
    text-decoration: none;
    color:white;
    font-size: 15px;
}
p {
    font-size: 20px;
}
{% endblock style %}

{% block content %}
<h1>Details of the book {{books.title}}</h1>
    <p>
    Title : {{books.title}} <br>
    Author : {{books.author}} <br>
    Price : {{books.price}} <br>
    </p>
    <a href="{% url 'books:index' %}"><button>Back</button></a>
    <a href="{% url 'books:update' books.id %}"><button>Edit Details</button></a>
    <a href="{% url 'books:delete' books.id %}"><button>Delete</button></a>
{% endblock content %}

books/templates/books/index.html
{% extends 'base.html' %}

{% block title %}
Books
{% endblock title %}

{% block style %}
.tooltip .tooltiptext {
    visibility: hidden;
    width: 120px;
    background-color: black;
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 5px 0;
    position: absolute;
    z-index: 1;
}

.tooltip:hover .tooltiptext {
    visibility: visible;
}

button {
    width: 150px;
    height: 30px;
    background-color: black;
    border-radius: 7px;
}
a button{
    text-decoration: none;
    color: white;
    font-size: 15px;
}

a {
    text-decoration: none;
    color: black;
    font-size: 15px;
}

li {
    font-size: 20px;
}
{% endblock style %}

{% block username %}
<p>#username : {{request.user}} </p>
{% endblock username %}

{% block content %}
<h1>Available Books</h1>
        <ul type="none">
            {% for book in Books %}
            <a href="{% url 'books:details' book.id %}">
                <div class="tooltip"><li>{{book}}</li><span class="tooltiptext">Click For More Info</span></div>
            </a>
            {% endfor %}
        </ul>
        <a href="{% url 'books:create' %}"><button>Add New Book</button></a>
        <a href="{% url 'logout' %}"><button>Logout</button></a>
{% endblock content %}

books/templates/books/update.html
{% extends 'base.html' %}

{% block title %}
Edit Details
{% endblock title %}

{% block style %}

input{
    margin: 3px;
    border-radius: 5px;
    border: solid 1px;
}
form{
    margin-bottom: 10px;

}
p{
    font-size: 20px;
}
button{
    width: 150px;
    height: 30px;
    background-color:black;
    border-radius: 7px;
}
button a{
    text-decoration: none;
    color:white;
    font-size: 15px;
}
#save{
    width: 150px;
    height: 30px;
    background-color:black;
    border-radius: 7px;
    color: white;
    font-size: 15px;
}
{% endblock style %}

{% block content %}
<h1>Edit details of the book {{books.title}}</h1>
        <form method="post">
        {% csrf_token %}
        <p>
        Name : <input type="text" name="title" value="{{books.title}}"><br>
        Author : <input type="text" name="author" value="{{books.author}}"><br>
        Price : <input type="number" name="price" value="{{books.price}}"><br></p>
        <button><a href="{% url 'books:details' books.id %}">Back</a></button>
        <input id="save" type="submit" value="Save">
    </form>
    {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <style>
        .container{
            margin: auto;
            margin-top: 200px;
            text-align: center;
            width: 500px;
            padding: 30px;
            background-image: linear-gradient(to top, #e0e6ee, #c5e4f9, #9de4fd, #68e5f7, #14e5e5);
            border-radius: 10px;
        }
        {% block style %}
        {% endblock style %}
    </style>
</head>
<body>
    {% block username %}
    {% endblock username %}
    <div class="container">
    {% block content %}
    {% endblock content %}
    </div>
</body>
</html>

templates/landing.html
{% extends 'base.html' %}

{% block title %}
Library App
{% endblock title %}

{% block style %}
#save{
    width: 150px;
    height: 30px;
    background-color:black;
    border-radius: 7px;
    color: white;
    font-size: 15px;
}
a{
    text-decoration:none;
    color: white;
    font-size: 15px 
}
{% endblock style %}

{% block content %}
<img src="/static/library.jpg" alt="No image">
<h1>Library Management System</h1>
        Already have an account?<br>
        <a href="{% url 'login' %}"><button id="save">Login</button></a><br><br>
        Doesn't have an account?<br>
        <a href="{% url 'signup' %}"><button id="save">Signup</button></a><br>
{% endblock content %}